# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='location',
            field=models.CharField(default='my location', max_length=120),
        ),
    ]
